# Generated by Django 3.2.5 on 2021-08-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='email',
            new_name='sub_email',
        ),
    ]
